export const NEW_MESSAGE_REQUEST = "NEW_MESSAGE_REQUEST";
export const NEW_MESSAGE_SUCCESS = "NEW_MESSAGE_SUCCESS";
export const NEW_MESSAGE_FAIL = "NEW_MESSAGE_FAIL";
export const NEW_MESSAGE_RESET = "NEW_MESSAGE_RESET";

export const ALL_MESSAGE_REQUEST = "ALL_MESSAGE_REQUEST";
export const ALL_MESSAGE_SUCCESS = "ALL_MESSAGE_SUCCESS";
export const ALL_MESSAGE_FAIL = "ALL_MESSAGE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";